// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    ConfigScreen: typeof import('./src/components/ConfigScreen.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    EntryEditor: typeof import('./src/components/EntryEditor.vue')['default']
    Field: typeof import('./src/components/Field.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}

export { }
